.PHONY: clean All

All:
	@echo "----------Building project:[ DynamicMemAllocation - Debug ]----------"
	@cd "DynamicMemAllocation" && "$(MAKE)" -f  "DynamicMemAllocation.mk"
clean:
	@echo "----------Cleaning project:[ DynamicMemAllocation - Debug ]----------"
	@cd "DynamicMemAllocation" && "$(MAKE)" -f  "DynamicMemAllocation.mk" clean
