.PHONY: clean All

All:
	@echo "----------Building project:[ rangeBasedForLoop - Debug ]----------"
	@cd "rangeBasedForLoop" && "$(MAKE)" -f  "rangeBasedForLoop.mk"
clean:
	@echo "----------Cleaning project:[ rangeBasedForLoop - Debug ]----------"
	@cd "rangeBasedForLoop" && "$(MAKE)" -f  "rangeBasedForLoop.mk" clean
