.PHONY: clean All

All:
	@echo "----------Building project:[ functionOverloading - Debug ]----------"
	@cd "functionOverloading" && "$(MAKE)" -f  "functionOverloading.mk"
clean:
	@echo "----------Cleaning project:[ functionOverloading - Debug ]----------"
	@cd "functionOverloading" && "$(MAKE)" -f  "functionOverloading.mk" clean
