.PHONY: clean All

All:
	@echo "----------Building project:[ defaultArguments - Debug ]----------"
	@cd "defaultArguments" && "$(MAKE)" -f  "defaultArguments.mk"
clean:
	@echo "----------Cleaning project:[ defaultArguments - Debug ]----------"
	@cd "defaultArguments" && "$(MAKE)" -f  "defaultArguments.mk" clean
