.PHONY: clean All

All:
	@echo "----------Building project:[ 01Mystring-start - Debug ]----------"
	@cd "01Mystring-start" && "$(MAKE)" -f  "01Mystring-start.mk"
clean:
	@echo "----------Cleaning project:[ 01Mystring-start - Debug ]----------"
	@cd "01Mystring-start" && "$(MAKE)" -f  "01Mystring-start.mk" clean
