.PHONY: clean All

All:
	@echo "----------Building project:[ 04Mystring-operator-methods - Debug ]----------"
	@cd "04Mystring-operator-methods" && "$(MAKE)" -f  "04Mystring-operator-methods.mk"
clean:
	@echo "----------Cleaning project:[ 04Mystring-operator-methods - Debug ]----------"
	@cd "04Mystring-operator-methods" && "$(MAKE)" -f  "04Mystring-operator-methods.mk" clean
